services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - "3306:3306"
